### ISSUE TITLE
Suggestion : change title color

### ISSUE THREAD

**Issue by kishore-polagani** [jaswanthsinghrasaputra/Git_Integration#1]
I think it looks better to have title , be little more orange color

```css
 h1 {
    color: #d69c37;
  }
```
